// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/hackathon/chasingcars/protocol/messages.proto

package com.hackathon.chasingcars.protocol;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WhoAmIOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string deviceAddr = 1;
    boolean hasDeviceAddr();
    String getDeviceAddr();
  }
  public static final class WhoAmI extends
      com.google.protobuf.GeneratedMessage
      implements WhoAmIOrBuilder {
    // Use WhoAmI.newBuilder() to construct.
    private WhoAmI(Builder builder) {
      super(builder);
    }
    private WhoAmI(boolean noInit) {}
    
    private static final WhoAmI defaultInstance;
    public static WhoAmI getDefaultInstance() {
      return defaultInstance;
    }
    
    public WhoAmI getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_WhoAmI_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_WhoAmI_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string deviceAddr = 1;
    public static final int DEVICEADDR_FIELD_NUMBER = 1;
    private java.lang.Object deviceAddr_;
    public boolean hasDeviceAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDeviceAddr() {
      java.lang.Object ref = deviceAddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceAddr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceAddrBytes() {
      java.lang.Object ref = deviceAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      deviceAddr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDeviceAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceAddrBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceAddrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.WhoAmI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hackathon.chasingcars.protocol.Messages.WhoAmI prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hackathon.chasingcars.protocol.Messages.WhoAmIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_WhoAmI_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_WhoAmI_fieldAccessorTable;
      }
      
      // Construct using com.hackathon.chasingcars.protocol.Messages.WhoAmI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hackathon.chasingcars.protocol.Messages.WhoAmI.getDescriptor();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.WhoAmI getDefaultInstanceForType() {
        return com.hackathon.chasingcars.protocol.Messages.WhoAmI.getDefaultInstance();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.WhoAmI build() {
        com.hackathon.chasingcars.protocol.Messages.WhoAmI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hackathon.chasingcars.protocol.Messages.WhoAmI buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hackathon.chasingcars.protocol.Messages.WhoAmI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hackathon.chasingcars.protocol.Messages.WhoAmI buildPartial() {
        com.hackathon.chasingcars.protocol.Messages.WhoAmI result = new com.hackathon.chasingcars.protocol.Messages.WhoAmI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceAddr_ = deviceAddr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hackathon.chasingcars.protocol.Messages.WhoAmI) {
          return mergeFrom((com.hackathon.chasingcars.protocol.Messages.WhoAmI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hackathon.chasingcars.protocol.Messages.WhoAmI other) {
        if (other == com.hackathon.chasingcars.protocol.Messages.WhoAmI.getDefaultInstance()) return this;
        if (other.hasDeviceAddr()) {
          setDeviceAddr(other.getDeviceAddr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDeviceAddr()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceAddr_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string deviceAddr = 1;
      private java.lang.Object deviceAddr_ = "";
      public boolean hasDeviceAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDeviceAddr() {
        java.lang.Object ref = deviceAddr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceAddr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceAddr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceAddr_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceAddr_ = getDefaultInstance().getDeviceAddr();
        onChanged();
        return this;
      }
      void setDeviceAddr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        deviceAddr_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:chasingcars.WhoAmI)
    }
    
    static {
      defaultInstance = new WhoAmI(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chasingcars.WhoAmI)
  }
  
  public interface YouAreOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string deviceAddr = 1;
    boolean hasDeviceAddr();
    String getDeviceAddr();
    
    // required int32 player = 2;
    boolean hasPlayer();
    int getPlayer();
  }
  public static final class YouAre extends
      com.google.protobuf.GeneratedMessage
      implements YouAreOrBuilder {
    // Use YouAre.newBuilder() to construct.
    private YouAre(Builder builder) {
      super(builder);
    }
    private YouAre(boolean noInit) {}
    
    private static final YouAre defaultInstance;
    public static YouAre getDefaultInstance() {
      return defaultInstance;
    }
    
    public YouAre getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_YouAre_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_YouAre_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string deviceAddr = 1;
    public static final int DEVICEADDR_FIELD_NUMBER = 1;
    private java.lang.Object deviceAddr_;
    public boolean hasDeviceAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDeviceAddr() {
      java.lang.Object ref = deviceAddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceAddr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceAddrBytes() {
      java.lang.Object ref = deviceAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 player = 2;
    public static final int PLAYER_FIELD_NUMBER = 2;
    private int player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPlayer() {
      return player_;
    }
    
    private void initFields() {
      deviceAddr_ = "";
      player_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDeviceAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceAddrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, player_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceAddrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, player_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.YouAre parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hackathon.chasingcars.protocol.Messages.YouAre prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hackathon.chasingcars.protocol.Messages.YouAreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_YouAre_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_YouAre_fieldAccessorTable;
      }
      
      // Construct using com.hackathon.chasingcars.protocol.Messages.YouAre.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        player_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hackathon.chasingcars.protocol.Messages.YouAre.getDescriptor();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.YouAre getDefaultInstanceForType() {
        return com.hackathon.chasingcars.protocol.Messages.YouAre.getDefaultInstance();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.YouAre build() {
        com.hackathon.chasingcars.protocol.Messages.YouAre result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hackathon.chasingcars.protocol.Messages.YouAre buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hackathon.chasingcars.protocol.Messages.YouAre result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hackathon.chasingcars.protocol.Messages.YouAre buildPartial() {
        com.hackathon.chasingcars.protocol.Messages.YouAre result = new com.hackathon.chasingcars.protocol.Messages.YouAre(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceAddr_ = deviceAddr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.player_ = player_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hackathon.chasingcars.protocol.Messages.YouAre) {
          return mergeFrom((com.hackathon.chasingcars.protocol.Messages.YouAre)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hackathon.chasingcars.protocol.Messages.YouAre other) {
        if (other == com.hackathon.chasingcars.protocol.Messages.YouAre.getDefaultInstance()) return this;
        if (other.hasDeviceAddr()) {
          setDeviceAddr(other.getDeviceAddr());
        }
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDeviceAddr()) {
          
          return false;
        }
        if (!hasPlayer()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceAddr_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              player_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string deviceAddr = 1;
      private java.lang.Object deviceAddr_ = "";
      public boolean hasDeviceAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDeviceAddr() {
        java.lang.Object ref = deviceAddr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceAddr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceAddr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceAddr_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceAddr_ = getDefaultInstance().getDeviceAddr();
        onChanged();
        return this;
      }
      void setDeviceAddr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        deviceAddr_ = value;
        onChanged();
      }
      
      // required int32 player = 2;
      private int player_ ;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPlayer() {
        return player_;
      }
      public Builder setPlayer(int value) {
        bitField0_ |= 0x00000002;
        player_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        player_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:chasingcars.YouAre)
    }
    
    static {
      defaultInstance = new YouAre(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chasingcars.YouAre)
  }
  
  public interface PlayerPosOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 player = 1;
    boolean hasPlayer();
    int getPlayer();
    
    // required int32 x = 2;
    boolean hasX();
    int getX();
    
    // required int32 y = 3;
    boolean hasY();
    int getY();
  }
  public static final class PlayerPos extends
      com.google.protobuf.GeneratedMessage
      implements PlayerPosOrBuilder {
    // Use PlayerPos.newBuilder() to construct.
    private PlayerPos(Builder builder) {
      super(builder);
    }
    private PlayerPos(boolean noInit) {}
    
    private static final PlayerPos defaultInstance;
    public static PlayerPos getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayerPos getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerPos_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerPos_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 player = 1;
    public static final int PLAYER_FIELD_NUMBER = 1;
    private int player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayer() {
      return player_;
    }
    
    // required int32 x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getX() {
      return x_;
    }
    
    // required int32 y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getY() {
      return y_;
    }
    
    private void initFields() {
      player_ = 0;
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, player_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, player_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerPos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hackathon.chasingcars.protocol.Messages.PlayerPos prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hackathon.chasingcars.protocol.Messages.PlayerPosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerPos_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerPos_fieldAccessorTable;
      }
      
      // Construct using com.hackathon.chasingcars.protocol.Messages.PlayerPos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        player_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hackathon.chasingcars.protocol.Messages.PlayerPos.getDescriptor();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.PlayerPos getDefaultInstanceForType() {
        return com.hackathon.chasingcars.protocol.Messages.PlayerPos.getDefaultInstance();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.PlayerPos build() {
        com.hackathon.chasingcars.protocol.Messages.PlayerPos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hackathon.chasingcars.protocol.Messages.PlayerPos buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hackathon.chasingcars.protocol.Messages.PlayerPos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hackathon.chasingcars.protocol.Messages.PlayerPos buildPartial() {
        com.hackathon.chasingcars.protocol.Messages.PlayerPos result = new com.hackathon.chasingcars.protocol.Messages.PlayerPos(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.player_ = player_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hackathon.chasingcars.protocol.Messages.PlayerPos) {
          return mergeFrom((com.hackathon.chasingcars.protocol.Messages.PlayerPos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hackathon.chasingcars.protocol.Messages.PlayerPos other) {
        if (other == com.hackathon.chasingcars.protocol.Messages.PlayerPos.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayer()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              player_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              x_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              y_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 player = 1;
      private int player_ ;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayer() {
        return player_;
      }
      public Builder setPlayer(int value) {
        bitField0_ |= 0x00000001;
        player_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        player_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 x = 2;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 y = 3;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:chasingcars.PlayerPos)
    }
    
    static {
      defaultInstance = new PlayerPos(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chasingcars.PlayerPos)
  }
  
  public interface PlayerCoinsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 player = 1;
    boolean hasPlayer();
    int getPlayer();
    
    // required int32 coins = 2;
    boolean hasCoins();
    int getCoins();
  }
  public static final class PlayerCoins extends
      com.google.protobuf.GeneratedMessage
      implements PlayerCoinsOrBuilder {
    // Use PlayerCoins.newBuilder() to construct.
    private PlayerCoins(Builder builder) {
      super(builder);
    }
    private PlayerCoins(boolean noInit) {}
    
    private static final PlayerCoins defaultInstance;
    public static PlayerCoins getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayerCoins getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerCoins_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerCoins_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 player = 1;
    public static final int PLAYER_FIELD_NUMBER = 1;
    private int player_;
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayer() {
      return player_;
    }
    
    // required int32 coins = 2;
    public static final int COINS_FIELD_NUMBER = 2;
    private int coins_;
    public boolean hasCoins() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCoins() {
      return coins_;
    }
    
    private void initFields() {
      player_ = 0;
      coins_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCoins()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, player_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, coins_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, player_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, coins_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.PlayerCoins parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hackathon.chasingcars.protocol.Messages.PlayerCoins prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hackathon.chasingcars.protocol.Messages.PlayerCoinsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerCoins_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_PlayerCoins_fieldAccessorTable;
      }
      
      // Construct using com.hackathon.chasingcars.protocol.Messages.PlayerCoins.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        player_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        coins_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hackathon.chasingcars.protocol.Messages.PlayerCoins.getDescriptor();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.PlayerCoins getDefaultInstanceForType() {
        return com.hackathon.chasingcars.protocol.Messages.PlayerCoins.getDefaultInstance();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.PlayerCoins build() {
        com.hackathon.chasingcars.protocol.Messages.PlayerCoins result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hackathon.chasingcars.protocol.Messages.PlayerCoins buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hackathon.chasingcars.protocol.Messages.PlayerCoins result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hackathon.chasingcars.protocol.Messages.PlayerCoins buildPartial() {
        com.hackathon.chasingcars.protocol.Messages.PlayerCoins result = new com.hackathon.chasingcars.protocol.Messages.PlayerCoins(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.player_ = player_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.coins_ = coins_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hackathon.chasingcars.protocol.Messages.PlayerCoins) {
          return mergeFrom((com.hackathon.chasingcars.protocol.Messages.PlayerCoins)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hackathon.chasingcars.protocol.Messages.PlayerCoins other) {
        if (other == com.hackathon.chasingcars.protocol.Messages.PlayerCoins.getDefaultInstance()) return this;
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        if (other.hasCoins()) {
          setCoins(other.getCoins());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayer()) {
          
          return false;
        }
        if (!hasCoins()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              player_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              coins_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 player = 1;
      private int player_ ;
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayer() {
        return player_;
      }
      public Builder setPlayer(int value) {
        bitField0_ |= 0x00000001;
        player_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        player_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 coins = 2;
      private int coins_ ;
      public boolean hasCoins() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCoins() {
        return coins_;
      }
      public Builder setCoins(int value) {
        bitField0_ |= 0x00000002;
        coins_ = value;
        onChanged();
        return this;
      }
      public Builder clearCoins() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coins_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:chasingcars.PlayerCoins)
    }
    
    static {
      defaultInstance = new PlayerCoins(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chasingcars.PlayerCoins)
  }
  
  public interface GameStartOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string time = 1;
    boolean hasTime();
    String getTime();
  }
  public static final class GameStart extends
      com.google.protobuf.GeneratedMessage
      implements GameStartOrBuilder {
    // Use GameStart.newBuilder() to construct.
    private GameStart(Builder builder) {
      super(builder);
    }
    private GameStart(boolean noInit) {}
    
    private static final GameStart defaultInstance;
    public static GameStart getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameStart getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameStart_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameStart_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      time_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameStart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hackathon.chasingcars.protocol.Messages.GameStart prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hackathon.chasingcars.protocol.Messages.GameStartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameStart_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameStart_fieldAccessorTable;
      }
      
      // Construct using com.hackathon.chasingcars.protocol.Messages.GameStart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hackathon.chasingcars.protocol.Messages.GameStart.getDescriptor();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.GameStart getDefaultInstanceForType() {
        return com.hackathon.chasingcars.protocol.Messages.GameStart.getDefaultInstance();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.GameStart build() {
        com.hackathon.chasingcars.protocol.Messages.GameStart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hackathon.chasingcars.protocol.Messages.GameStart buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hackathon.chasingcars.protocol.Messages.GameStart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hackathon.chasingcars.protocol.Messages.GameStart buildPartial() {
        com.hackathon.chasingcars.protocol.Messages.GameStart result = new com.hackathon.chasingcars.protocol.Messages.GameStart(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hackathon.chasingcars.protocol.Messages.GameStart) {
          return mergeFrom((com.hackathon.chasingcars.protocol.Messages.GameStart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hackathon.chasingcars.protocol.Messages.GameStart other) {
        if (other == com.hackathon.chasingcars.protocol.Messages.GameStart.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              time_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string time = 1;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:chasingcars.GameStart)
    }
    
    static {
      defaultInstance = new GameStart(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chasingcars.GameStart)
  }
  
  public interface GameEndOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string time = 1;
    boolean hasTime();
    String getTime();
  }
  public static final class GameEnd extends
      com.google.protobuf.GeneratedMessage
      implements GameEndOrBuilder {
    // Use GameEnd.newBuilder() to construct.
    private GameEnd(Builder builder) {
      super(builder);
    }
    private GameEnd(boolean noInit) {}
    
    private static final GameEnd defaultInstance;
    public static GameEnd getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameEnd getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameEnd_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameEnd_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      time_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hackathon.chasingcars.protocol.Messages.GameEnd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hackathon.chasingcars.protocol.Messages.GameEnd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hackathon.chasingcars.protocol.Messages.GameEndOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameEnd_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hackathon.chasingcars.protocol.Messages.internal_static_chasingcars_GameEnd_fieldAccessorTable;
      }
      
      // Construct using com.hackathon.chasingcars.protocol.Messages.GameEnd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hackathon.chasingcars.protocol.Messages.GameEnd.getDescriptor();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.GameEnd getDefaultInstanceForType() {
        return com.hackathon.chasingcars.protocol.Messages.GameEnd.getDefaultInstance();
      }
      
      public com.hackathon.chasingcars.protocol.Messages.GameEnd build() {
        com.hackathon.chasingcars.protocol.Messages.GameEnd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hackathon.chasingcars.protocol.Messages.GameEnd buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hackathon.chasingcars.protocol.Messages.GameEnd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hackathon.chasingcars.protocol.Messages.GameEnd buildPartial() {
        com.hackathon.chasingcars.protocol.Messages.GameEnd result = new com.hackathon.chasingcars.protocol.Messages.GameEnd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hackathon.chasingcars.protocol.Messages.GameEnd) {
          return mergeFrom((com.hackathon.chasingcars.protocol.Messages.GameEnd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hackathon.chasingcars.protocol.Messages.GameEnd other) {
        if (other == com.hackathon.chasingcars.protocol.Messages.GameEnd.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              time_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string time = 1;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:chasingcars.GameEnd)
    }
    
    static {
      defaultInstance = new GameEnd(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chasingcars.GameEnd)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chasingcars_WhoAmI_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chasingcars_WhoAmI_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chasingcars_YouAre_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chasingcars_YouAre_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chasingcars_PlayerPos_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chasingcars_PlayerPos_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chasingcars_PlayerCoins_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chasingcars_PlayerCoins_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chasingcars_GameStart_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chasingcars_GameStart_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chasingcars_GameEnd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chasingcars_GameEnd_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1com/hackathon/chasingcars/protocol/mes" +
      "sages.proto\022\013chasingcars\"\034\n\006WhoAmI\022\022\n\nde" +
      "viceAddr\030\001 \002(\t\",\n\006YouAre\022\022\n\ndeviceAddr\030\001" +
      " \002(\t\022\016\n\006player\030\002 \002(\005\"1\n\tPlayerPos\022\016\n\006pla" +
      "yer\030\001 \002(\005\022\t\n\001x\030\002 \002(\005\022\t\n\001y\030\003 \002(\005\",\n\013Playe" +
      "rCoins\022\016\n\006player\030\001 \002(\005\022\r\n\005coins\030\002 \002(\005\"\031\n" +
      "\tGameStart\022\014\n\004time\030\001 \002(\t\"\027\n\007GameEnd\022\014\n\004t" +
      "ime\030\001 \002(\tB.\n\"com.hackathon.chasingcars.p" +
      "rotocolB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_chasingcars_WhoAmI_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_chasingcars_WhoAmI_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chasingcars_WhoAmI_descriptor,
              new java.lang.String[] { "DeviceAddr", },
              com.hackathon.chasingcars.protocol.Messages.WhoAmI.class,
              com.hackathon.chasingcars.protocol.Messages.WhoAmI.Builder.class);
          internal_static_chasingcars_YouAre_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_chasingcars_YouAre_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chasingcars_YouAre_descriptor,
              new java.lang.String[] { "DeviceAddr", "Player", },
              com.hackathon.chasingcars.protocol.Messages.YouAre.class,
              com.hackathon.chasingcars.protocol.Messages.YouAre.Builder.class);
          internal_static_chasingcars_PlayerPos_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_chasingcars_PlayerPos_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chasingcars_PlayerPos_descriptor,
              new java.lang.String[] { "Player", "X", "Y", },
              com.hackathon.chasingcars.protocol.Messages.PlayerPos.class,
              com.hackathon.chasingcars.protocol.Messages.PlayerPos.Builder.class);
          internal_static_chasingcars_PlayerCoins_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_chasingcars_PlayerCoins_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chasingcars_PlayerCoins_descriptor,
              new java.lang.String[] { "Player", "Coins", },
              com.hackathon.chasingcars.protocol.Messages.PlayerCoins.class,
              com.hackathon.chasingcars.protocol.Messages.PlayerCoins.Builder.class);
          internal_static_chasingcars_GameStart_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_chasingcars_GameStart_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chasingcars_GameStart_descriptor,
              new java.lang.String[] { "Time", },
              com.hackathon.chasingcars.protocol.Messages.GameStart.class,
              com.hackathon.chasingcars.protocol.Messages.GameStart.Builder.class);
          internal_static_chasingcars_GameEnd_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_chasingcars_GameEnd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chasingcars_GameEnd_descriptor,
              new java.lang.String[] { "Time", },
              com.hackathon.chasingcars.protocol.Messages.GameEnd.class,
              com.hackathon.chasingcars.protocol.Messages.GameEnd.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
